Decision Tree:
  criterion:
    type: combo
    options: [gini, entropy, log_loss]
    default: gini
    help: Split quality function
  max_depth:
    type: numeric
    default: None
    help: Max depth (None=unbounded)

Random Forest:
  n_estimators:
    type: numeric
    default: "100"
    help: Number of trees (e.g. 50-300)
  criterion:
    type: combo
    options: [gini, entropy, log_loss]
    default: gini
    help: Split quality function
  max_depth:
    type: numeric
    default: None
    help: Max depth (None=unbounded)

Extra Trees:
  n_estimators:
    type: numeric
    default: "100"
    help: Number of trees (e.g. 50-300)
  criterion:
    type: combo
    options: [gini, entropy, log_loss]
    default: gini
    help: Split quality function
  max_depth:
    type: numeric
    default: None
    help: Max depth (None=unbounded)

KNN:
  n_neighbors:
    type: numeric
    default: "5"
    help: Number of neighbors (1-20 typical)
  weights:
    type: combo
    options: [uniform, distance]
    default: uniform
    help: Uniform or distance-based weighting

SVM:
  kernel:
    type: combo
    options: [linear, rbf, poly, sigmoid]
    default: rbf
    help: SVM kernel type
  C:
    type: numeric
    default: "1.0"
    help: Regularization strength (0.001-100)

LDA:
  solver:
    type: combo
    options: [svd, lsqr, eigen]
    default: svd
    help: LDA solver

Logistic Regression:
  solver:
    type: combo
    options: [lbfgs, newton-cg, liblinear, sag, saga]
    default: lbfgs
    help: Solver for optimization
  max_iter:
    type: numeric
    default: "1000"
    help: Max iteration count
  C:
    type: numeric
    default: "1.0"
    help: Inverse reg. strength (0.001-100)

Ridge:
  alpha:
    type: numeric
    default: "1.0"
    help: Regularization strength (0.0+)

Naive Bayes:
  var_smoothing:
    type: numeric
    default: "1e-9"
    help: Stability var. (1e-12 ~ 1e-7 typical)

MLP:
  hidden_layer_sizes:
    type: text
    default: (100, )
    help: Layer sizes tuple, e.g. (100,50)
  activation:
    type: combo
    options: [identity, logistic, tanh, relu]
    default: relu
    help: Activation function
  solver:
    type: combo
    options: [lbfgs, sgd, adam]
    default: adam
    help: MLP solver
  alpha:
    type: numeric
    default: "0.0001"
    help: L2 penalty parameter
  max_iter:
    type: numeric
    default: "1000"
    help: Max training iterations

SGD:
  loss:
    type: combo
    options: [hinge, log, modified_huber, squared_hinge, perceptron]
    default: hinge
    help: Loss function
  penalty:
    type: combo
    options: [l2, l1, elasticnet]
    default: l2
    help: Regularization type
  alpha:
    type: numeric
    default: "0.0001"
    help: Constant for regularization

Gradient Boosting:
  n_estimators:
    type: numeric
    default: "100"
    help: Number of boosting stages
  learning_rate:
    type: numeric
    default: "0.1"
    help: Learning rate (0.01-1.0 typical)
  max_depth:
    type: numeric
    default: "3"
    help: Max depth (1-10 typical)

AdaBoost:
  n_estimators:
    type: numeric
    default: "100"
    help: Number of boosting stages
  learning_rate:
    type: numeric
    default: "1.0"
    help: Weight applied to each classifier

XGBoost:
  n_estimators:
    type: numeric
    default: "100"
    help: Number of boosting rounds
  learning_rate:
    type: numeric
    default: "0.1"
    help: Step size shrinkage (0.01-0.3 typical)
  max_depth:
    type: numeric
    default: "3"
    help: Max tree depth (1-10 typical) 